---
- name: Create group for Ignite
  become: true
  ansible.builtin.group:
    name: "{{ ignite_group }}"
    state: present

- name: Create user for Ignite
  become: true
  ansible.builtin.user:
    name: "{{ ignite_owner }}"
    group: "{{ ignite_group }}"
    groups: ""
    append: false
    password: "!"
    expires: -1
    state: present
