---

- name: Create ignite dirs before install
  become: yes
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ ignite_owner}}"
    group: "{{ ignite_group }}"
  loop:
    - "{{ ignite_distr_dir }}"
    - "{{ ignite_tmp_dir }}"
    - "{{ ignite_bin_dir}}"
    - "{{ ignite_config_dir }}"
    - "{{ ignite_libs_dir }}"
    - "{{ ignite_user_libs_dir }}"
    - "{{ ignite_logs_dir }}"
