---
# tasks file for install_apache_ignite
- include_tasks: stop_ignite.yml

- include_tasks: delete_ignite_before_install.yml

- include_tasks: create_ignite_dirs_before_install.yml

- include_tasks: install_ignite.yml

- include_tasks: clean_after_install.yml

